version: 2

updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "xylar"
      - "altheaden"
    reviewers:
      - "xylar"
      - "altheaden"
      - "andrewdnolan"

