name: TEST
dependencies:
  - python=3.7
  - pytest
  - six
  - numpy
  - scipy
  - lxml
  - xarray >=0.14.1
  - matplotlib >=3.0.2
  - dask
  - netcdf4
  - hdf5
  - hdf4
  - nco >=4.8.1
  - pyproj
  - pillow
  - cmocean
  - progressbar2
  - requests
  - shapely
  - basemap
  - cartopy
  - geometric_features
  - gsw
  - pyremap
  - sphinx
  - mock
  - sphinx_rtd_theme
  - numpydoc
  - tabulate >=0.8.2
  - m2r
