name: mpas-analysis-docs
channels:
  - conda-forge
dependencies:
  - python=2.7
  - pytest
  - numpy
  - scipy
  - matplotlib
  - netcdf4
  - xarray
  - dask
  - bottleneck
  - basemap
  - lxml
  - hdf5
  - hdf4
  - nco
  - pyproj
  - pillow
  - sphinx
  - sphinx_rtd_theme
  - numpydoc
  - tabulate
  - pip:
    - recommonmark
